language: node_js

node_js:
  - "0.12"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm run lint

script:
  - npm test
  - npm run build-examples
  - npm run deploy-examples

cache:
  directories:
    - node_modules